### ISSUE TITLE
Generate NEWS.md with kwb.pkgbuild::use_news_md()

### ISSUE THREAD

**Issue by mrustl** [KWB-R/kwb.readxl#1]
Function docu: https://kwb-r.github.io/kwb.pkgbuild/dev/reference/use_news_md.html

Output: https://kwb-r.github.io/kwb.pkgbuild/dev/news/index.html

**Comment by hsonne** [comment]
Ich gehe jetzt erst mal Beachvolleyball spielen!

**Comment by mrustl** [comment]
Have fun!

**Comment by mrustl** [comment]
Done in https://github.com/KWB-R/kwb.readxl/commit/2d728ded8fbed00cbe0a6dbbc6cea2511b87a754
